### PR TITLE
Error reset

### PR DESCRIPTION
**Pull request by clefebvre**

### CODE REVIEW

**Comment by lestcape** [comment]
> but in my testing ubuntu-drivers selected the open ones no matter what. Is that not the case?

If i remember properly that was not my case on Ubuntu. It recommended the open center, but i can change the selection. I'm on Debian now and is difficult said something here because i modify a lot of things.

Does ubuntu-drivers suggest non-free when appropriate? 

Well that is a confused question as the open driver is also non-free. There are 3 types of drivers now:

1. The [open](https://github.com/NVIDIA/open-gpu-kernel-modules) (that is also non-free), just the header are free and merged in the Linux kernel but not the driver itself.
2. The free (the [nouveau](https://nouveau.freedesktop.org/) driver).
3. The [proprietary](https://www.nvidia.com/Download/index.aspx) (the one that always was propietary).

> Superior as in open-source vs. proprietary? Or as in, it's actually a better driver? I couldn't find that in the comments.

I don't know really why hi said that, but he also made a review (open vs proprietary) here:
https://www.phoronix.com/review/nvidia-r515-open/2

**Comment by mtwebster** [comment]
I skimmed thru ubuntu-drivers-common, it looks like it does try to make a determination whether or not to suggest an -open driver, maybe we'll revert that commit.

**Comment by lestcape** [comment]
I don't think he try hard to detect the good one:
https://github.com/tseliot/ubuntu-drivers-common/commit/d835980d1a1e051c1034d4c155dd30a90f2379e5

But that was never my point. Select the recommended one is pointless to me. Give the user the final decision of what driver he want to install is the point to me.

**Comment by leigh123linux** [comment]
Does the open driver still require the proprietary gsp firmware to function?
According to their readme they class it as alpha quality, so it should be hidden IMO.

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/README.md

**Comment by lestcape** [comment]
> Does the open driver still require the proprietary gsp firmware to function?

Yes, the only thing that is open is the kernel module, the driver itself is still closed.

> According to their read me they class it as alpha quality, so it should be hidden IMO.

Well, said like that, you're going to be right. But this is not how almost all people see it. Also this only can hidden the package from a GUI, because the package is already in the Ubuntu and Debian repositories. If we consider the open driver as alpha, what do we leave for then to the free driver that works 100 times worse?

**Pull request merged**
